import React from 'react';
import Header from './Header';
import Footer from './Footer';

const PrivacyPolicyPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      <Header />
      
      <main className="flex-grow container mx-auto px-4 py-10 md:py-16">
        <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-sm border border-gray-100 p-6 md:p-10">
          <h1 className="text-3xl md:text-4xl font-bold text-gray-800 mb-6">Privacy Policy</h1>
          
          <p className="text-gray-600 mb-8">
            Adventures in Speech Pathology ("us", "we", or "our") operates the https://adventuresinspeechpathology.com website (the "Service").
            This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
          </p>
          
          <p className="text-gray-600 mb-8">
            We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://adventuresinspeechpathology.com
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Understanding the Definitions</h2>
          
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Service</h3>
              <p className="text-gray-600">
                Service is the https://adventuresinspeechpathology.com website operated by Adventures in Speech Pathology
              </p>
            </div>
            
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Personal Data</h3>
              <p className="text-gray-600">
                Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
              </p>
            </div>
            
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Usage Data</h3>
              <p className="text-gray-600">
                Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
              </p>
            </div>
            
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Cookies</h3>
              <p className="text-gray-600">
                Cookies are small pieces of data stored on your device (computer or mobile device).
              </p>
            </div>
            
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Data Controller</h3>
              <p className="text-gray-600">
                Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.
                For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
              </p>
            </div>
            
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Data Processors (or Service Providers)</h3>
              <p className="text-gray-600">
                Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.
                We may use the services of various Service Providers in order to process your data more effectively.
              </p>
            </div>
            
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Data Subject (or User)</h3>
              <p className="text-gray-600">
                Data Subject is any living individual who is using our Service and is the subject of Personal Data.
              </p>
            </div>
          </div>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">How Collected Information is Used</h2>
          
          <p className="text-gray-600 mb-8">
            We collect several different types of information for various purposes to provide and improve our Service to you.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Types of Data Collected</h2>
          
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Personal Data</h3>
              <p className="text-gray-600 mb-4">
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
              </p>
              
              <ul className="list-disc pl-6 space-y-1 text-gray-600">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Cookies and Usage Data</li>
              </ul>
              
              <p className="text-gray-600 mt-4">
                We may use your Personal Data to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.
              </p>
            </div>
            
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Usage Data</h3>
              <p className="text-gray-600">
                We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
            </div>
            
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Tracking & Cookies Data</h3>
              <p className="text-gray-600 mb-4">
                We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
                Cookies are files with a small amount of data that may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
              </p>
              
              <p className="text-gray-600 mb-2">Examples of Cookies we use:</p>
              <ul className="list-disc pl-6 space-y-1 text-gray-600">
                <li><span className="font-medium">Session Cookies.</span> We use Session Cookies to operate our Service.</li>
                <li><span className="font-medium">Preference Cookies.</span> We use Preference Cookies to remember your preferences and various settings.</li>
                <li><span className="font-medium">Security Cookies.</span> We use Security Cookies for security purposes.</li>
              </ul>
            </div>
          </div>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Use of Data</h2>
          
          <p className="text-gray-600 mb-4">
            Adventures in Speech Pathology uses the collected data for various purposes:
          </p>
          
          <ul className="list-disc pl-6 space-y-1 text-gray-600">
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>To provide you with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
          </ul>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</h2>
          
          <p className="text-gray-600 mb-4">
            If you are from the European Economic Area (EEA), Adventures in Speech Pathology's legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
            Adventures in Speech Pathology may process your Personal Data because:
          </p>
          
          <ul className="list-disc pl-6 space-y-1 text-gray-600">
            <li>We need to perform a contract with you</li>
            <li>You have given us permission to do so</li>
            <li>The processing is in our legitimate interests and it's not overridden by your rights</li>
            <li>To comply with the law</li>
          </ul>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Retention of Data</h2>
          
          <p className="text-gray-600 mb-4">
            Adventures in Speech Pathology will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </p>
          
          <p className="text-gray-600">
            Adventures in Speech Pathology will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Transfer Of Data</h2>
          
          <p className="text-gray-600 mb-4">
            Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those from your jurisdiction.
          </p>
          
          <p className="text-gray-600 mb-4">
            If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.
          </p>
          
          <p className="text-gray-600 mb-4">
            Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
          </p>
          
          <p className="text-gray-600">
            Adventures in Speech Pathology will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Disclosure Of Data</h2>
          
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Disclosure for Law Enforcement</h3>
              <p className="text-gray-600">
                Under certain circumstances, Adventures in Speech Pathology may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
              </p>
            </div>
            
            <div>
              <h3 className="text-lg font-bold text-gray-800 mb-2">Legal Requirements</h3>
              <p className="text-gray-600 mb-4">
                Adventures in Speech Pathology may disclose your Personal Data in the good faith belief that such action is necessary to:
              </p>
              
              <ul className="list-disc pl-6 space-y-1 text-gray-600">
                <li>To comply with a legal obligation</li>
                <li>To protect and defend the rights or property of Adventures in Speech Pathology</li>
                <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                <li>To protect the personal safety of users of the Service or the public</li>
                <li>To protect against legal liability</li>
              </ul>
            </div>
          </div>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Security Of Data</h2>
          
          <p className="text-gray-600">
            The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">"Do Not Track" Signals</h2>
          
          <p className="text-gray-600">
            We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
          </p>
          
          <p className="text-gray-600">
            You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
          
          <p className="text-gray-600 mb-4">
            If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Adventures in Speech Pathology aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
          </p>
          
          <p className="text-gray-600 mb-4">
            If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
          </p>
          
          <p className="text-gray-600 mb-4">
            In certain circumstances, you have the following data protection rights:
          </p>
          
          <ul className="list-disc pl-6 space-y-1 text-gray-600">
            <li>
              <span className="font-medium">The right to access, update or delete</span> the information we have on you. Whenever made possible, you can access, update, or request the deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.
            </li>
            <li>
              <span className="font-medium">The right of rectification.</span> You have the right to have your information rectified if that information is inaccurate or incomplete.
            </li>
            <li>
              <span className="font-medium">The right to object.</span> You have the right to object to our processing of your Personal Data.
            </li>
            <li>
              <span className="font-medium">The right of restriction.</span> You have the right to request that we restrict the processing of your personal information.
            </li>
            <li>
              <span className="font-medium">The right to data portability.</span> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable, and commonly used format.
            </li>
            <li>
              <span className="font-medium">The right to withdraw consent.</span> You also have the right to withdraw your consent at any time where Adventures in Speech Pathology relied on your consent to process your personal information.
            </li>
          </ul>
          
          <p className="text-gray-600 mt-4">
            Please note that we may ask you to verify your identity before responding to such requests.
          </p>
          
          <p className="text-gray-600">
            You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Service Providers</h2>
          
          <p className="text-gray-600 mb-4">
            We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services, or to assist us in analyzing how our Service is used.
          </p>
          
          <p className="text-gray-600">
            These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Analytics</h2>
          
          <p className="text-gray-600 mb-4">
            We may use third-party Service Providers to monitor and analyze the use of our Service.
          </p>
          
          <div className="bg-gray-50 p-5 rounded-xl border border-gray-200 mb-4">
            <h3 className="text-lg font-bold text-gray-800 mb-2">Google Analytics</h3>
            <p className="text-gray-600 mb-2">
              Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
            </p>
            
            <p className="text-gray-600 mb-2">
              You can opt out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.
            </p>
            
            <p className="text-gray-600">
              For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="http://www.google.com/intl/en/policies/privacy/" className="text-[#2bcd82] hover:underline">http://www.google.com/intl/en/policies/privacy/</a>
            </p>
          </div>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Behavioral Remarketing</h2>
          
          <p className="text-gray-600 mb-4">
            Adventures in Speech Pathology uses remarketing services to advertise on third-party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.
          </p>
          
          <div className="space-y-6">
            <div className="bg-gray-50 p-5 rounded-xl border border-gray-200">
              <h3 className="text-lg font-bold text-gray-800 mb-2">Google AdWords</h3>
              <p className="text-gray-600 mb-2">
                Google AdWords remarketing service is provided by Google Inc.
              </p>
              
              <p className="text-gray-600 mb-2">
                You can opt out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: <a href="http://www.google.com/settings/ads" className="text-[#2bcd82] hover:underline">http://www.google.com/settings/ads</a>
              </p>
              
              <p className="text-gray-600 mb-2">
                Google also recommends installing the Google Analytics Opt-out Browser Add-on – <a href="https://tools.google.com/dlpage/gaoptout" className="text-[#2bcd82] hover:underline">https://tools.google.com/dlpage/gaoptout</a> – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.
              </p>
              
              <p className="text-gray-600">
                For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="http://www.google.com/intl/en/policies/privacy/" className="text-[#2bcd82] hover:underline">http://www.google.com/intl/en/policies/privacy/</a>
              </p>
            </div>
            
            <div className="bg-gray-50 p-5 rounded-xl border border-gray-200">
              <h3 className="text-lg font-bold text-gray-800 mb-2">Facebook</h3>
              <p className="text-gray-600 mb-2">
                Facebook remarketing service is provided by Facebook Inc.
              </p>
              
              <p className="text-gray-600 mb-2">
                You can learn more about interest-based advertising from Facebook by visiting this page: <a href="https://www.facebook.com/help/164968693837950" className="text-[#2bcd82] hover:underline">https://www.facebook.com/help/164968693837950</a>
              </p>
              
              <p className="text-gray-600 mb-2">
                To opt-out from Facebook's interest-based ads follow these instructions from Facebook: <a href="https://www.facebook.com/help/568137493302217" className="text-[#2bcd82] hover:underline">https://www.facebook.com/help/568137493302217</a>
              </p>
              
              <p className="text-gray-600 mb-2">
                Facebook adheres to the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital Advertising Alliance. You can also opt out from Facebook and other participating companies through the Digital Advertising Alliance in the USA <a href="http://www.aboutads.info/choices/" className="text-[#2bcd82] hover:underline">http://www.aboutads.info/choices/</a>, the Digital Advertising Alliance of Canada in Canada <a href="http://youradchoices.ca/" className="text-[#2bcd82] hover:underline">http://youradchoices.ca/</a> or the European Interactive Digital Advertising Alliance in Europe <a href="http://www.youronlinechoices.eu/" className="text-[#2bcd82] hover:underline">http://www.youronlinechoices.eu/</a>, or opt-out using your mobile device settings.
              </p>
              
              <p className="text-gray-600">
                For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: <a href="https://www.facebook.com/privacy/explanation" className="text-[#2bcd82] hover:underline">https://www.facebook.com/privacy/explanation</a>
              </p>
            </div>
            
            <div className="bg-gray-50 p-5 rounded-xl border border-gray-200">
              <h3 className="text-lg font-bold text-gray-800 mb-2">Pinterest</h3>
              <p className="text-gray-600 mb-2">
                Pinterest remarketing service is provided by Pinterest Inc.
              </p>
              
              <p className="text-gray-600 mb-2">
                You can opt out from Pinterest's interest-based ads by enabling the "Do Not Track" functionality of your web browser or by following Pinterest instructions: <a href="http://help.pinterest.com/en/articles/personalization-and-data" className="text-[#2bcd82] hover:underline">http://help.pinterest.com/en/articles/personalization-and-data</a>
              </p>
              
              <p className="text-gray-600">
                You can learn more about the privacy practices and policies of Pinterest by visiting their Privacy Policy page: <a href="https://about.pinterest.com/en/privacy-policy" className="text-[#2bcd82] hover:underline">https://about.pinterest.com/en/privacy-policy</a>
              </p>
            </div>
          </div>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Links To Other Sites</h2>
          
          <p className="text-gray-600 mb-4">
            Our Service may contain links to other sites that are not operated by us. If you click on a third-party link, you will be directed to that third-party's site. We strongly advise you to review the Privacy Policy of every site you visit.
          </p>
          
          <p className="text-gray-600">
            We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Children's Privacy</h2>
          
          <p className="text-gray-600 mb-4">
            Our Service does not address anyone under the age of 18 ("Children").
          </p>
          
          <p className="text-gray-600">
            We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children have provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Changes To This Privacy Policy</h2>
          
          <p className="text-gray-600 mb-4">
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
          </p>
          
          <p className="text-gray-600 mb-4">
            We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective, and update the "effective date" at the top of this Privacy Policy.
          </p>
          
          <p className="text-gray-600">
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>
          
          <h2 className="text-2xl font-bold text-gray-800 mt-10 mb-4">Contact Us</h2>
          
          <p className="text-gray-600 mb-4">
            If you have any questions about this Privacy Policy, please contact us:
          </p>
          
          <p className="text-gray-600">
            By email: <a href="mailto:support@adventuresinspeechpathology.com" className="text-[#2bcd82] hover:underline">support@adventuresinspeechpathology.com</a>
          </p>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default PrivacyPolicyPage; 